### ISSUE TITLE
Vulkan: Use of previously acquired images from retired Swapchains results in crash

### ISSUE THREAD

**Issue by DarathDev** [GPUOpen-Drivers/AMD-Gfx-Drivers#62]
## Problem
An exception is thrown when performing any operation that involves an acquired image from a retired swapchain. Specifically, I have seen this behaviour with the creation of pipeline barriers, and present operations.

This seems to conflict with the Vulkan spec for [VkSwapchainCreateInfoKHR](https://registry.khronos.org/vulkan/specs/latest/man/html/VkSwapchainCreateInfoKHR.html)

> After oldSwapchain is retired, the application can pass to [vkQueuePresentKHR](https://registry.khronos.org/vulkan/specs/latest/man/html/vkQueuePresentKHR.html) any images it had already acquired from oldSwapchain. E.g., an application may present an image from the old swapchain before an image from the new swapchain is ready to be presented. As usual, [vkQueuePresentKHR](https://registry.khronos.org/vulkan/specs/latest/man/html/vkQueuePresentKHR.html) may fail if oldSwapchain has entered a state that causes VK_ERROR_OUT_OF_DATE_KHR to be returned.

> The application can continue to use a shared presentable image obtained from oldSwapchain until a presentable image is acquired from the new swapchain, as long as it has not entered a state that causes it to return VK_ERROR_OUT_OF_DATE_KHR.

## Steps to Reproduce:

1. Create a swapchain
2. Acquire an image
3. Create a new swapchain on the same surface, with the first swapchain as the parameter for oldSwapchain
4. Perform an operation with the acquired image (imageMemoryBarrier, present, etc.)

No validation errors are thrown prior.

## Expected Behaviour

Either the operation succeeds, or in the case of VkQueuePresentKHR it returns a VkResult value that reflects the issue like VK_ERROR_OUT_OF_DATE_KHR

Apologies for not having a minimal reproducible sample.

Connected System Information

Driver Version: 25.10.13.01-250526a-416003C-AMD-Software-Adrenalin-Edition
GPUOpen Interface Major Version: 42

Operating System Name: Windows 11 Pro
Operating System Description: 26100.1.amd64fre.ge_release.240331-1435

GPUs:
******************************************
Name: AMD Radeon RX 7900 XT

ASIC info
************
Device Id: 744C
Revision: CC
Family: 91
gfx_engine: 13

******************************************
Name: AMD Radeon(TM) Graphics

ASIC info
************
Device Id: 164E
Revision: C3
Family: 95
gfx_engine: 13

[DxDiag.txt](https://github.com/user-attachments/files/21498957/DxDiag.txt)

**Comment by DarathDev** [comment]
I have also tried leaving the oldSwapchain null, which should result in createSwapchain returning VK_ERROR_NATIVE_WINDOW_IN_USE_KHR, instead I get VK_ERROR_FORMAT_NOT_SUPPORTED

**Comment by pperucki-AMD** [comment]
Any chance of getting a sample code reproducing the issue? That would speed up having a fix done.

**Comment by DarathDev** [comment]
I'm using .NET bindings to the Vulkan Api, which I doubt is particularly useful for you. 
On that note, while I doubt its an issue with with the bindings themselves, I cannot guarantee that.

**Comment by pperucki-AMD** [comment]
We weren’t able to reproduce this issue. Can you check if it still happens with the newest driver?
Would it be possible for you to provide a minimal project that exposes the problem? The .NET Vulkan binding is not a blocker — as long as the project can be compiled and run locally, we’ll be able to handle it.

**Comment by DarathDev** [comment]
I will try with the new driver, and if it still happens I will see about getting you a min repro.

**Comment by pperucki-AMD** [comment]
@DarathDev did you have a chance to check with the latest driver?

**Comment by DarathDev** [comment]
Sorry for the delay, I have checked with the latest driver and I still run into this issue. I've made a reproducible sample in Odin for Windows which rules out it being an issue with the bindings. 

The most relevant code is found on lines 117-122 and 1160 - 1220

[Sample](https://gist.github.com/DarathDev/083fe6142db50ebfb7cae9c13e23ded7)

**Comment by skart0196-AMD** [comment]
Hey @DarathDev , we did have an issue with presenting from a retired swapchain that was fixed internally recently but I'm not sure if you can perform other operations on a retired image.

The language you quote

> The application can continue to use a shared presentable image obtained from oldSwapchain until a presentable image is acquired from the new swapchain, as long as it has not entered a state that causes it to return VK_ERROR_OUT_OF_DATE_KHR.

I believe only applies to swapchains created in one of the shared present modes i.e. `VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR ` and `VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR`

**Comment by DarathDev** [comment]
I just checked with directly presenting and that is still failing
```
Driver Version: 25.20.29.09-251203a-196284C-AMD-Software-Adrenalin-Edition
GPUOpen Interface Major Version: 42
```
I assume that as you say it will be resolved when that internal fix becomes public.

---

Thanks for catching that mistake. I was operating under a false assumption, that it was fine to use a 'retired sub-optimally acquired image' for rendering.

I also just double checked the spec, and I now see that it is acceptable to destroy the swapchain without presenting all of it's acquired images.

I can check my code again when that fix goes public, or if you're certain it's the same problem you can close the issue.

**Comment by skart0196-AMD** [comment]
> I assume that as you say it will be resolved when that internal fix becomes public.
> 
> Thanks for catching that mistake. I was operating under a false assumption, that it was fine to use a 'retired sub-optimally acquired image' for rendering.
> 
> I also just double checked the spec, and I now see that it is acceptable to destroy the swapchain without presenting all of it's acquired images.
> 
> I can check my code again when that fix goes public, or if you're certain it's the same problem you can close the issue.


Yeah, I don't believe the internal fix is public yet. I'm quite positive that we fixed the exact issue you described but we can keep this thread open and I will ping you once I know the fix has made it into a public release so you can verify.
